//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_batch_audit
    {
        public int pk { get; set; }
        public short entry_type { get; set; }
        public System.DateTime entry_time { get; set; }
        public Nullable<short> primary_key_type { get; set; }
        public string primary_key { get; set; }
        public Nullable<short> secondary_key_type { get; set; }
        public string secondary_key { get; set; }
        public Nullable<short> third_key_type { get; set; }
        public string third_key { get; set; }
        public Nullable<int> reference { get; set; }
        public Nullable<int> batch_run_num { get; set; }
        public Nullable<int> batch_id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<int> error_no { get; set; }
        public string description { get; set; }
        public Nullable<int> assigned_team_no { get; set; }
        public Nullable<int> assigned_user_id { get; set; }
        public Nullable<int> chunk_id { get; set; }
        public string server_name { get; set; }
        public Nullable<int> pid { get; set; }
        public int discriminator { get; set; }
    }
}
