//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_operational_data
    {
        public int pk { get; set; }
        public int policy_no { get; set; }
        public short opening_status { get; set; }
        public System.DateTime opening_reg_date { get; set; }
        public System.DateTime opening_effec_date { get; set; }
        public string opening_ref { get; set; }
        public short closing_status { get; set; }
        public Nullable<System.DateTime> closing_reg_date { get; set; }
        public Nullable<System.DateTime> closing_effec_date { get; set; }
        public string closing_ref { get; set; }
        public short product { get; set; }
        public short version { get; set; }
        public Nullable<short> premium_linkage_code { get; set; }
        public Nullable<decimal> premium_linkage_value { get; set; }
        public Nullable<short> auto_withdrawal_code { get; set; }
        public Nullable<decimal> auto_withdrawal_amount { get; set; }
        public Nullable<short> auto_withdrawal_freq { get; set; }
        public Nullable<short> auto_withdraw_payment_method { get; set; }
        public Nullable<short> auto_withdraw_beneficiary_role { get; set; }
        public Nullable<int> number_of_segments { get; set; }
        public Nullable<int> remaining_number_of_segments { get; set; }
        public Nullable<short> manual_segmentation_flag { get; set; }
        public Nullable<short> arrears_stage { get; set; }
        public Nullable<System.DateTime> arrears_stage_date { get; set; }
        public Nullable<short> follow_scheme_investment_code { get; set; }
        public Nullable<short> follow_scheme_contrbution_code { get; set; }
        public string general_desc { get; set; }
        public Nullable<int> user_id { get; set; }
        public short calc_status { get; set; }
        public Nullable<int> assigned_team_no { get; set; }
        public Nullable<int> assigned_user_id { get; set; }
        public Nullable<short> branch { get; set; }
        public Nullable<int> salesperson_no { get; set; }
        public Nullable<short> manual_credit_reduction_flag { get; set; }
        public Nullable<decimal> sales_credit_reduction_percent { get; set; }
        public Nullable<short> inland_revenue_regime { get; set; }
        public Nullable<short> manual_ir_regime_flag { get; set; }
        public Nullable<short> manual_no_admin_fee_flag { get; set; }
        public short no_admin_fee_flag { get; set; }
        public Nullable<short> manual_no_bid_offer_sprd_flag { get; set; }
        public short no_bid_offer_spread_flag { get; set; }
        public Nullable<short> manual_fund_series_flag { get; set; }
        public Nullable<short> fund_series { get; set; }
        public Nullable<short> follow_scheme_covers_code { get; set; }
        public Nullable<short> follow_scheme_switch_code { get; set; }
        public Nullable<System.DateTime> legal_contract_date { get; set; }
        public Nullable<short> de_minimis_flag { get; set; }
        public Nullable<short> trust_status { get; set; }
        public Nullable<System.DateTime> trust_declaration_date { get; set; }
        public Nullable<short> form_of_nomination { get; set; }
        public short follow_scheme_stepped_amc_code { get; set; }
        public Nullable<short> class_of_administration { get; set; }
        public Nullable<short> member_category_of_status { get; set; }
        public short amarct_flag { get; set; }
        public Nullable<int> arrears_days_till_next_stage { get; set; }
        public Nullable<short> arrears_cycle_suspended { get; set; }
        public Nullable<System.DateTime> arrears_next_review_date { get; set; }
        public Nullable<short> arrears_collect_debt_in_bill { get; set; }
        public Nullable<decimal> arrears_max_amt_to_collect { get; set; }
        public short money_laundering_section { get; set; }
        public short advice_given { get; set; }
        public short manual_admin_fee_amount_flag { get; set; }
        public Nullable<decimal> manual_admin_fee_amount { get; set; }
        public Nullable<short> frequency_statement { get; set; }
        public Nullable<System.DateTime> next_issue_date_statement { get; set; }
        public Nullable<System.DateTime> next_start_date_statement { get; set; }
        public Nullable<System.DateTime> next_end_date_statement { get; set; }
        public Nullable<short> statement_hold_flag { get; set; }
        public Nullable<short> follow_template_statement_flag { get; set; }
        public Nullable<System.DateTime> last_issue_date_statement { get; set; }
        public Nullable<short> welcome_pack_issued_flag { get; set; }
        public Nullable<short> trust_sub_status { get; set; }
        public Nullable<short> tax_framework { get; set; }
        public Nullable<short> annual_calc_flag { get; set; }
        public Nullable<short> tax_in_source_flag { get; set; }
        public string policy_an_ref { get; set; }
        public Nullable<short> capital_gain_flag { get; set; }
        public Nullable<double> capital_gain_percent { get; set; }
        public Nullable<double> policy_premium_driven_amount { get; set; }
        public Nullable<short> policy_premium_driven_flag { get; set; }
        public Nullable<short> policy_residency { get; set; }
        public Nullable<short> premium_freeze_flag { get; set; }
        public short stop_loss_flag { get; set; }
        public Nullable<decimal> stop_loss_percent { get; set; }
        public Nullable<System.DateTime> temporary_risk_start_date { get; set; }
        public Nullable<System.DateTime> temporary_risk_end_date { get; set; }
        public Nullable<decimal> target_fund_value_amount { get; set; }
        public Nullable<decimal> budget_premium_amount { get; set; }
        public int application_issue_state { get; set; }
        public Nullable<short> apl_code { get; set; }
        public Nullable<short> default_non_forfeiture_option { get; set; }
        public Nullable<System.DateTime> policy_issue_date { get; set; }
        public Nullable<short> manual_issue_date_flag { get; set; }
        public Nullable<int> manual_issue_user_id { get; set; }
        public Nullable<short> band_no { get; set; }
        public Nullable<System.DateTime> next_non_renewal_anniversary { get; set; }
        public Nullable<decimal> budget_sum_assured_amount { get; set; }
        public Nullable<decimal> budget_perm_term_split { get; set; }
        public Nullable<short> skip_billing_format_code { get; set; }
        public Nullable<short> inherited_policy { get; set; }
        public short recalculate_covers_flag { get; set; }
        public int discriminator { get; set; }
        public Nullable<short> escalation_method { get; set; }
        public Nullable<decimal> escalation_perc { get; set; }
        public Nullable<short> escalation_index_type { get; set; }
        public Nullable<System.DateTime> orig_closing_reg_date { get; set; }
        public Nullable<System.DateTime> orig_closing_effec_date { get; set; }
        public Nullable<short> orig_closing_status { get; set; }
        public string orig_closing_ref { get; set; }
        public short escalation_period { get; set; }
    }
}
