//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_auth_data
    {
        public string dbms { get; set; }
        public string db_name { get; set; }
        public string log_id { get; set; }
        public string log_pw { get; set; }
        public string server_name { get; set; }
        public string dbparm { get; set; }
        public short default_data { get; set; }
        public int company_id { get; set; }
        public string company_name { get; set; }
        public string sec_db_name { get; set; }
        public string web_company_id { get; set; }
        public Nullable<short> external_authentication_code { get; set; }
        public short show_flag { get; set; }
        public string linked_server { get; set; }
        public string j2ee_datasource { get; set; }
        public string jdbc_connect_string { get; set; }
        public string driver { get; set; }
        public string port_number { get; set; }
        public string schema_name { get; set; }
        public string rdbms { get; set; }
        public int uniqid { get; set; }
        public string driver_params { get; set; }
        public int discriminator { get; set; }
    }
}
