//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_batch
    {
        public int batch_id { get; set; }
        public string batch_name { get; set; }
        public short status { get; set; }
        public Nullable<short> output_frequency { get; set; }
        public short commit_flag { get; set; }
        public Nullable<short> details_group { get; set; }
        public Nullable<short> max_db_errors { get; set; }
        public Nullable<short> ol_activation_code { get; set; }
        public Nullable<short> auto_activation_code { get; set; }
        public int entity_key { get; set; }
        public int uniqid { get; set; }
        public int discriminator { get; set; }
    }
}
