//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_task
    {
        public int task_id { get; set; }
        public string task_name { get; set; }
        public System.DateTime opening_reg_date { get; set; }
        public int opening_user_id { get; set; }
        public short interface_type { get; set; }
        public string entry_point_name { get; set; }
        public string task_run_name { get; set; }
        public short commit_frequency { get; set; }
        public string comment_text { get; set; }
        public int entity_key { get; set; }
        public Nullable<int> post_task { get; set; }
        public Nullable<int> pre_task { get; set; }
        public Nullable<int> chunk_param { get; set; }
        public Nullable<int> chunk_flag { get; set; }
        public Nullable<int> chunk_type { get; set; }
        public int failure_action { get; set; }
        public int timeout_seconds { get; set; }
        public int num_retries { get; set; }
        public int counter_inc { get; set; }
        public Nullable<short> max_items_before_memory_claen { get; set; }
        public int uniqid { get; set; }
        public int discriminator { get; set; }
        public int activity_code { get; set; }
    }
}
